export class PermanencyRelease {
    valueArr = [
        { Office: 'Office' },
        { SocialWorker: 'Social Worker' },
        { email: 'Email form to' },
        { DateOfRelease: 'Date of Permanency or Release' },
        { PreviousPlacementName: 'Previous Placement Name' },
        { PreviousPlacementAddress: 'Previous Placement Address' },
        { PreviousPlacementSchool: 'Previous Placement School' },
        { PreviousPlacementLevelOfCare: 'Previous Placement Level of Care' },
        { PermanencyPlacementName: 'Permanency Placement Name' },
        { PermanencyPlacementAddress: 'Permanency Placement Address' },
        { PermanencyPlacementPhone: 'Permanency Placement Phone' },
        { PermanencyPlacementSchool: 'Permanency Placement School' },
        { HighestGradeCompleted: 'Highest Grade Completed' },
        { ChangeOfVenueTo: 'Change of Venue To' },
        { DateCountAcceptedVenue: 'Date County Accepted Venue' },
        { NewCourtCaseNo: 'New Court Case#' },
        { NewDCFWorker: 'New DCF Worker' },
        { Judge: 'Judge' },
        { CompletionDate: 'Date' }
    ];

    optionIndex = [
        { REUNI: 'Returned Home (REUNI)' },
        { CustodialParent: 'Custodial Parent' },
        { NonCustodialParent: 'Non-Custodial Parent' },
        { APASigned: 'APA Signed' },
        { Released: 'DCF Released of Custody' },
        { AdoptivePlacement: 'Adoptive Placement Finalized (ADOPT)' },
        { DirectPlacement: 'Direct Placement' },
        { Relative: 'Relative' },
        { NonRelatives: 'Non-Relatives' },
        { AgedOut: 'Youth Aged Out' },
        { ReturnedHome: 'Returned Home and DCF Released of Custody (REUNI)' },
        { custodial_Parent: 'Custodial Parent' },
        { nonCustodial_Parent: 'Non-Custodial Parent' },
        { KDOC: 'KDOC (Unless dually adjudicated)' },
        { Custodianship: 'Custodianship/Guardianship & DCF Releases of Custody' },
        { ChildDeath: 'Child Death' },
        { AfterCareLivingOutOfState: 'After Care Completed (Living out of State -No ICPC)' },
        { DCFRetraction: 'DCF Retraction' },
        { AfterCareCompleted: 'After Care Completed (365 Days)' },
        { InitiatedDCF: 'DCF' },
        { InitiatedSFCS: 'SFCS' },
        { InitiatedCourt: 'Court' },
    ]
}