export class WorkerChild {
    valueArr = [
        { caseNo: 'Case Number' },
        { CompletionDate: 'Date' },
        { FromTime: 'From' },
        { ToTime: 'To' },
        { Place: 'If visit is outside of placement, specify place' },
        { presentAtVisit: 'List those present at visit' },
        { DescriptionAndCommentsByChild: 'Describe location of visit, length of time, items discussed, and list any comments made by the child' },
        { placementEnvironment: 'Describe the placement environment' },
        { childAppearance: 'Describe the child’s appearance' },
        { interactionWithCaregiver: 'Observed interaction with caregiver' },
        { safetyConcernsIndentified: 'If applicable, what safety concerns have been identified since last visit' },
        { familySafetyMitigationStrengths: 'What are the family’s strengths and resources mitigating safety concerns' },
        { safetyConcernsContributingFactors: 'What are the contributing factors directly related to the safety concern' },
        { placementEnvironmentRiskSection: 'Describe the placement environment' },
        { childsAppearance: 'Describe the child’s appearance' },
        { interactionWithCaregiverRiskSection: 'Observed interaction with caregiver' },
        { safetyConcernsSinceLastVisit: 'If applicable, what risk concerns have been identified since last visit' },
        { visitDetailsRiskSection: 'What are the family’s strengths and resources mitigating risk concerns' },
        { serviceMitigateConcerns: 'What services are needed or have taken place to mitigate the concerns' },
        { medication: 'List medication changes since last W/C visit' },
        { appointments: 'List all appointments since last W/C visit' },
        { maintaining: 'How is the child is maintaining important connections' },
        { extracurricular: 'List extracurricular activities' },
        { school: 'Describe how child is doing in school/day care' },
        { ReviewOfLifeSkillsTransitionPlan: 'Summary & Review of Life Skills/Transition Plan' },
        { ReviewOfPermanencyPlanAfterCarePlanProgress: 'Summary & Review of Permanency Plan, After Care Plan, Safety Plan, Service Plan and Progress' },
        { AdditionalRemarksPositivesOrConcerns: '  Additional Comments (Pertains to information discussed but not addressed above)' },
        { Follow: 'FOLLOW-UP ACTIVITIES IDENTIFIED DURING VISIT' },
        { PersonResponsible: 'PERSON RESPONSIBLE' },
        { TargetDate: 'TARGET DATE' },
        { Scheduled: 'Next W/C Visit Scheduled For' },
        { Signature: 'Signature/Title' },
    ];

    singleArr = [
        { proCode: 'Procode' }
    ];

    optionIndex = [
        { DidWorkerSpendTimeAloneWithChild: 'Did worker spend time alone with child' },
        { PlacementSupportiveofMeeting: 'Placement supportive of worker meeting with child' },
        { casePlanGoal: 'visit type' },
        { HomeIsFreeOfSafetyConcerns: 'Home is free of safety concerns' },
        { ChildsAppearanceIsHealthy: 'Child appearance is healthy' },
        { HomeIsClean: 'Home is clean' },
        { FreeFromUnusualMarksOrBruising: 'Free from unusual marks or bruising' },
        { homicidalThoughts: 'Homicidal Thoughts or Gestures' },
        { suicidalThoughts: 'Suicidal Thoughts or Gestures' },
        { caregiverProtectiveCapacity: 'Caregiver has the protective capacity ability to care for the child' },
        { additionalSafetyConcerns: 'Have additional risk concerns been identified since last visit' },
        { SafetyPlanReviewed: 'Safety plan developed or reviewed' },
        { Changeinplacementhousehold: 'Change in placement household' },
        { HeightandWeightappearnormal: 'Height and Weight appear normal' },
        { ChildHasAdequateSpace: 'Child has adequate space' },
        { ChildisCleanNeatlyGroomed: 'Child is clean, neatly groomed' },
        { caregiverNaturalAndCommunitySupports: 'Caregiver has natural and community supports' },
        { ChildFeelsSafeAndTreatedWell: 'Child feels safe and treated well' },
        { caregiverDemonstratesAbilityToProvideCare: 'Caregiver demonstrates the ability to provide adequate care for the child' },
        { displayedSelfHarmingBehavior: 'Child has displayed self-harming behaviors' },
        { displayedAgressiveBehavior: 'Child has displayed aggressive behaviors' },
        { additionalSafetyConcernsSinceLastVisit: 'Have additional risk concerns been identified since last visit' },
        { HasInteractionsWithParents: 'Has interactions with parents' },
        { HasInteractionsWithSiblings: 'Has interactions with siblings' },
        { MaintainingOtherImportantConnections: 'Maintaining other important connections' },
        { AttendingMentalHealthAppointments: 'Attending mental health appointments' },
        { Medical: 'Medical/Vision/Dental current' },
        { LifeBookIsUpdated: 'Life Book is updated' },
        { Adequate: 'Adequate opportunities for sleep' },
        { FeelsParentInteractionsAreGoingWell: 'Feels parent interactions are going well' },
        { FeelsSiblingInteractionsAreGoingWell: 'Feels sibling interactions are going well' },
        { Participatesinextracurricular: 'Participates in extracurricular activities' },
        { AttendingSchoolRegularly: 'Attending school regularly' },
        { AdjustingToSchoolSverageGrades: 'Adjusting to school & average grades' },
        { TakingMedicationsAsPrescribed: 'Taking medications as prescribed' },
        { Provided: 'Provided' },
        { information: 'Worker contact information provided to youth' },
        { informationprovided: 'How was information provided' },
        { CaseTeamMember: 'Case Team Member' }
    ]
}