export class AdoptiveInquiry {
    valueArr = [
        { CompletionDate: 'Date' },
        { childWorker: 'Child’s Worker' },
        { DateOfBirth: 'DOB' },
        { ClientPhone1: 'Phone Number' },
        { ClientPhone2: 'Phone Number' },
        { FamilyName: 'Name' },
        { FamilyAddress: 'Address' },
        { FamilyPhone: 'Telephone Number' },
        { FamilyEmail: 'Email Address' },
        { ChildrenInTheHome1: 'Children in the Home Name 1' },
        { ChildrenInTheHomeAge1: 'Children in the Home Age 1' },
        { ChildrenInTheHome2: 'Children in the Home Name 2' },
        { ChildrenInTheHomeAge2: 'Children in the Home Age 2' },
        { ChildrenInTheHome3: 'Children in the Home Name 3' },
        { ChildrenInTheHomeAGe3: 'Children in the Home Age 3' },
        { ChildrenInTheHome4: 'Children in the Home Name 4' },
        { ChildrenInTheHomeAge4: 'Children in the Home Age 4' },
        { ChildrenInTheHome5: 'Children in the Home Name 5' },
        { ChildrenInTheHomeAge5: 'Children in the Home Age 5' },
        { OtherIndividuals1: 'Other Individuals in the Home Name 1' },
        { OtherIndividualsAge1: 'Other Individuals in the Home Age 1' },
        { OtherIndividuals2: 'Other Individuals in the Home Name 2' },
        { OtherIndividualsAge2: 'Other Individuals in the Home Age 2' },
        { OtherIndividuals3: 'Other Individuals in the Home Name 3' },
        { OtherIndividualsAge3: 'Other Individuals in the Home Age 3' },
        { OtherIndividuals4: 'Other Individuals in the Home Name 4' },
        { OtherIndividualsAge4: 'Other Individuals in the Home Age 4' },
        { OtherIndividuals5: 'Other Individuals in the Home Name 5' },
        { OtherIndividualsAge5: 'Other Individuals in the Home Age 5' },
        { SponsoringAgency: 'If so, please list the sponsoring agency and foster care worker' },
        { PastState: 'If so, what state' },
        { Motivation: 'What is the family’s motivation to adopt' },
        { AwareOfChild: 'How did the family become aware of the child' },
        { Relationship: 'What is the family’s relationship with the child' },
        { concerns: 'Are you aware of any concerns regarding this resource or issues to be explored during the assessment process' },
        { SiblingsOutOfHomeName1: 'Siblings in Out of Home Care Name 1' },
        { SiblingsOutOfHomeAge1: 'Siblings in Out of Home Care Age 1' },
        { SiblingsOutOfHomeCaseplangoal1: 'Siblings in Out of Home Care Case Plan Goal 1' },
        { SiblingsOutOfHomeName2: 'Siblings in Out of Home Care Name 2' },
        { SiblingsOutOfHomeAge2: 'Siblings in Out of Home Care Age 2' },
        { SiblingsOutOfHomeCaseplangoal2: 'Siblings in Out of Home Care Case Plan Goal 2' },
        { SiblingsOutOfHomeName3: 'Siblings in Out of Home Care Name 3' },
        { SiblingsOutOfHomeAge3: 'Siblings in Out of Home Care Age 3' },
        { SiblingsOutOfHomeCaseplangoal3: 'Siblings in Out of Home Care Case Plan Goal 3' },
        { SiblingsOutOfHomeName4: 'Siblings in Out of Home Care Name 4' },
        { SiblingsOutOfHomeAge4: 'Siblings in Out of Home Care Age 4' },
        { SiblingsOutOfHomeCaseplangoal4: 'Siblings in Out of Home Care Case Plan Goal 4' },
        { SiblingsOutOfHomeName5: 'Siblings in Out of Home Care Name 5' },
        { SiblingsOutOfHomeAge5: 'Siblings in Out of Home Care Age 5' },
        { SiblingsOutOfHomeCaseplangoal5: 'Siblings in Out of Home Care Case Plan Goal 5' },
        { SiblingsOutOfHomeName6: 'Siblings in Out of Home Care Name 6' },
        { SiblingsOutOfHomeAge6: 'Siblings in Out of Home Care Age 6' },
        { SiblingsOutOfHomeCaseplangoal6: 'Siblings in Out of Home Care Case Plan Goal 6 ' }
    ];

    optionIndex = [
        { ps: 'PS-MAPP/DT Completed' },
        { KinshipPlacement: 'Is this resource the child’s Kinship Placement' },
        { AssessmentCompleted: 'Has a Kinship Assessment been completed on the family' },
        { licensed: 'Is the inquiring family a licensed foster home' },
        { AnotherState: 'Has the family lived in another state within the past 5 years' },
        { ResourceForSiblings: 'Is the inquiring family a resource for the siblings' },
        { ResourceForSibling: 'If so, which siblings' },
        { ApprovedSplit: 'If not, is there an approved sibling split' }
    ];
}