export class ProgressNotes {
  progressNoteID: number;
  clientID: any;
  beginDate: any;
  endDate: any;
  therapist_StaffID: any;
  location: string;
  therapyTypeID: any;
  isFaceToFace = false;
  isTelemedicine = false;
  isInteractiveComplexity = false;
  participants: string;
  objectiveAddressed: string;
  newProblems: string;
  topicsCovered: string;
  changeTXPlan: string;
  diagnosisChange: string;
  prognosisTypeID: number;
  gafValue: number;
  homeSafetyConcerns_YesNoPendingID: number;
  childAppearsHealthy_YesNoPendingID: number;
  homeIsClean_YesNoPendingID: number;
  heightWeight_YesNoPendingID: number;
  childIsClean_YesNoPendingID: number;
  unusualMarks_YesNoPendingID: number;
  additionalComments: string;
  nextAppointmentDate: any;
  isLastAppointment = false;
  planTillNextAppointment: string;
  statusTypeID: number;
  medicalNecessityID: number[];
  mentalStatusID: number[];
  referralID: number;
  caseActivityID: number;
  communityResourceUpdate: any;
  clientFunctionating: any;
  caseActivityFaceToFace: any;

  isAgreementStatementChecked = false;
  isTreatmentNeeded = false;
  isMoodDisordered = false;
  isContinuedImpairment = false;
  isInterpersonalImpairment = false;
  isImpairmentInSocial = false;
  isMeetsContinue = false;
  isServicesNecessary = false;
  isMonitorMedication = false;
  isSevere = false;
  isModerate = false;
  isMild = false;
  isMinimal = false;
  isNone = false;
  isEuthymic = false;
  isDepressed = false;
  isIrritable = false;
  isAnxious = false;
  isEuphoric = false;
  isOther = false;
  isNoImpairment = false;
  isDisorganized = false;
  isPoorConcentration = false;
  isImpairedAbstract = false;
  isImpairedJudgement = false;
  isBlunted = false;
  isRestricted = false;
  isIntense = false;
  isAppropritate = false;
  isFlat = false;
  isDetached = false;
  isDangeNone = false;
  isIdeation = false;
  isPlan = false;
  isGestures = false;
  isOngoingConcern = false;
  suicidalThoughtsOrGestures_YesNoPendingID: number;
  violentThoughtsOrGestures_YesNoPendingID: number;
  weaponsObserved_YesNoPendingID: number;
  caregiverforTheChild_YesNoPendingID: number;
  caregiverInfluenceOfSubstances_YesNoPendingID: number;
  newSafetyConcerns_YesNoPendingID: number;
  developedORreviewed_YesNoPendingID: number;
  familySafetyPlan: string;
  safetyNeeds: string;
  safetyComments: string;
  householdMembers_YesNoPendingID: number;
  naturalAndCommunitySupports_YesNoPendingID: number;
  hygieneAndDress_YesNoPendingID: number;
  caregiverDemonstrates_YesNoPendingID: number;
  selfHarmingBehaviors_YesNoPendingID: number;
  aggressiveBehaviors_YesNoPendingID: number;
  adequateSpace_YesNoPendingID: number;
  additionalRiskConcerns_YesNoPendingID: number;
  casePlanOrNonIntensive_YesNoPendingID: number;
  familyStrengthsAndResources: string;
  riskComments: string;
  originatingSite: string;
  distantSite: string;
  individualTherapy = false;
  groupTherapy = false;
  psychInterview = false;
  caseConference = false;
  therapyInHome = false;
  therapyInClinic = false;
}

export class ProgressNotesPrint {
  topicsCovered: string;
  therapyType: any;
  caseName: any;
  caseNumber: any;
  date: any;
  dateOfReferral: any;
  startTime: any;
  endTime: any;
  clientLocation: any;
  sessionParticipants: any;
  goalsObjectives: any;
  gafValue: any;
  clientFunctionating: any;
  changeTXPlan: any;
  diagnosisChange: any;
  homeSafetyConcerns: any;
  nextAppointmentDate: any;
  childAppearanceHealthy: any;
  homeRelativelyClean: any;
  heightWeightAppear: any;
  isChildClean: any;
  unusualMarks: any;
  additionalComments: any;
  isTreatmentNeeded = false;
  isMoodDisordered = false;
  isContinuedImpairment = false;
  isInterpersonalImpairment = false;
  isImpairmentInSocial = false;
  isMeetsContinue = false;
  isServicesNecessary = false;
  isMonitorMedication = false;
  isAgreementStatementChecked = false;

  isSevere = false;
  isModerate = false;
  isMild = false;
  isMinimal = false;
  isNone = false;
  isEuthymic = false;
  isDepressed = false;
  isIrritable = false;
  isAnxious = false;
  isEuphoric = false;
  isOther = false;
  isNoImpairment = false;
  isDisorganized = false;
  isPoorConcentration = false;
  isImpairedAbstract = false;
  isImpairedJudgement = false;
  isBlunted = false;
  isRestricted = false;
  isIntense = false;
  isAppropritate = false;
  isFlat = false;
  isDetached = false;
  isDangeNone = false;
  isIdeation = false;
  isPlan = false;
  isGestures = false;
  isOngoingConcern = false;

  isInitialPsychInterview = false;
  isIndividualTherapy = false;
  isFamilyTherapyInHome = false;
  isGroupTherapy = false;
  isFamilyTherapyInClinic = false;
  isCaseConferance = false;
  isGood = false;
  isFair = false;
  isGuarded = false;
  isPoor = false;

  suicidalThoughtsOrGestures_YesNoPendingID: number;
  violentThoughtsOrGestures_YesNoPendingID: number;
  weaponsObserved_YesNoPendingID: number;
  caregiverforTheChild_YesNoPendingID: number;
  caregiverInfluenceOfSubstances_YesNoPendingID: number;
  newSafetyConcerns_YesNoPendingID: number;
  developedORreviewed_YesNoPendingID: number;
  familySafetyPlan: string;
  safetyNeeds: string;
  safetyComments: string;
  householdMembers_YesNoPendingID: number;
  naturalAndCommunitySupports_YesNoPendingID: number;
  hygieneAndDress_YesNoPendingID: number;
  caregiverDemonstrates_YesNoPendingID: number;
  selfHarmingBehaviors_YesNoPendingID: number;
  aggressiveBehaviors_YesNoPendingID: number;
  adequateSpace_YesNoPendingID: number;
  additionalRiskConcerns_YesNoPendingID: number;
  casePlanOrNonIntensive_YesNoPendingID: number;
  familyStrengthsAndResources: string;
  riskComments: string;
  homeSafetyConcerns_YesNoPendingID: number;
  homeIsClean_YesNoPendingID: number;
  childAppearsHealthy_YesNoPendingID: number;
  unusualMarks_YesNoPendingID: number;
  heightWeight_YesNoPendingID: number;
  diagnosisCodeID: any;
  planTillNextAppointment: any;
  originatingSite: string;
  distantSite: string;
  individualTherapy = false;
  groupTherapy = false;
  psychInterview = false;
  caseConference = false;
  therapyInHome = false;
  therapyInClinic = false;
  officeLocation: string;
}

export class encounter {
  caseName: any;
  caseNumber: any;
  date: any;
  dateOfReferral: any;
  startTime: any;
  endTime: any;
  dob: any;
  program: any;
  contractClient: any;
  location: any;
  isFaceToFace: any;
  isTelemedicine: any;
  isInteractiveComplexity: any;
  time: any;
  units: any;
  procode: any;
  chargeAmount: any;
  therapist: any;
  diagnosisCodeID: any;
}
export class medicalNecessary {
  isTreatmentNeeded = false;
  isContinuedImpairment = false;
  isImpairmentInSocial = false;
  isServicesNecessary = false;
  isMoodDisordered = false;
  isInterpersonalImpairment = false;
  isMeetsContinue = false;
  isMonitorMedication = false;
}

export class mentalStatus {
  mentalStatusOther: any;
  remarks: any;
  isSevere = false;
  isModerate = false;
  isMild = false;
  isMinimal = false;
  isNone = false;
  isEuthymic = false;
  isDepressed = false;
  isIrritable = false;
  isAnxious = false;
  isEuphoric = false;
  isOther = false;
  isNoImpairment = false;
  isDisorganized = false;
  isPoorConcentration = false;
  isImpairedAbstract = false;
  isImpairedJudgement = false;
  isBlunted = false;
  isRestricted = false;
  isIntense = false;
  isAppropritate = false;
  isFlat = false;
  isDetached = false;
  isDangeNone = false;
  isIdeation = false;
  isPlan = false;
  isGestures = false;
  isOngoingConcern = false;
}

export class therapyTypes {
  isInitialPsychInterview = false;
  isIndividualTherapy = false;
  isFamilyTherapyInHome = false;
  isGroupTherapy = false;
  isFamilyTherapyInClinic = false;
  isCaseConferance = false;
}
export class ProgressNoteDiagnosis {
  clientID: any;
  beginDate: any;
  endDate: any;
  isPrimary = false;
  diagnosisCodeID: any;
  clarification: String;
  referralID: number;
  progressNoteDiagnosisID: any;
  classificationID: any;
  isCode: any;
}
