export class Crops {
    valueArr: any[] = [
        { ClientName: 'Client Name' },
        { CompletionDate: 'Date of Completion' },
        { BTotal: 'Total Score: 1-26 (except for item 24)' },
        { CTotal: 'Instructions to Youth' },

    ]
    optionIndex = [
        { CROPS_Question1: 'I daydream (I have dreamlike thoughts while awake)' },
        { CROPS_Question2: 'I "space out" when people are talking to me (I get distracted when people are talking to me)' },
        { CROPS_Question3: 'I find it hard to concentrate' },
        { CROPS_Question4: 'I think about bad things that have happened.' },
        { CROPS_Question5: 'I try to forget about bad things that have happened' },
        { CROPS_Question6: 'I avoid reminders of bad things that have happened' },
        { CROPS_Question7: 'I worry that bad things will happen' },
        { CROPS_Question8: 'I do special things to make sure nothing bad happens' },
        { CROPS_Question9: 'I do some things that Im probably too old for' },
        { CROPS_Question10: ' Things make me upset or mad' },
        { CROPS_Question11: 'It is hard for me to go to sleep at night' },
        { CROPS_Question12: 'I have bad dreams or nightmares' },
        { CROPS_Question13: 'I get headaches' },
        { CROPS_Question14: 'I get stomach aches' },
        { CROPS_Question15: 'I feel sick or have pains' },
        { CROPS_Question16: 'I feel tired or low energy' },
        { CROPS_Question17: 'I feel all alone' },
        { CROPS_Question18: 'I feel strange or different than other kids' },
        { CROPS_Question19: 'I feel like there’s something wrong with me' },
        { CROPS_Question20: 'I feel like it’s my fault when bad things happen.' },
        { CROPS_Question21: 'I’m a jinx, or bad-luck charm (bad things happen because I’m around)' },
        { CROPS_Question22: 'I feel sad or depressed' },
        { CROPS_Question23: 'I don’t feel like doing much' },
        { CROPS_Question24: 'My future looks bad' },
        { CROPS_Question25: 'I’m on the lookout for bad things that might happen' },
        { CROPS_Question26: 'I am nervous or jumpy' },
        { CROPS_Question27: 'been in a storm, tornado, flood or fire that destroyed your house or school?' },
        { CROPS_Question28: 'seen or been in an accident or were you hurt really badly?' },
        { CROPS_Question29: 'had to go to the hospital because you were really sick or hurt?' },
        { CROPS_Question30: 'been threatened or hit, punched, kicked or choked by another child or an adult?' },
        { CROPS_Question31: 'had anyone threatened to or touched, looked at or take pictures of your private parts? Has anyone ever asked you to touch or look at their private parts?' },
        { CROPS_Question32: 'seen one of your parents punch, beat, shove, kick, or hurt your other parent in any way?' },
        { CROPS_Question33: 'watched someone in your neighborhood get really hurt or die?' },
        { CROPS_Question34: 'been removed from your home and had to live with another family or in another home?' },
        { CROPS_Question35: 'been left alone for long periods of time, had to go without enough food and/or had to miss a lot of days of school?' },
        { CROPS_Question36: 'been bullied (called names, pushed, stole your things, or threatened) by others? or treated badly because of your skin color, religion, money/ clothes, LGBTQ, or because you were in foster care?' },
        { CROPS_Question37: 'seen one of your parents struggle with depression (very sad) or other mental illness (very angry or seeing/hearing voices when nothing was there) or with their use of street or prescription drugs or alcohol?' },
        { CROPS_Question38: 'had someone who was close to you (e.g., parent, caregiver, sibling, friend) that is not there anymore maybe because they are in jail, in college, in the army, or they died or were deported?' },
        { CROPS_Question39: 'felt that no one really loved or cared for you or felt that you were all alone?' },
        { CROPS_Question40: 'Did I forget to ask you about anything that may have happened to you?' },
    ]
    quesId = [
        'CROPS_Question1', 'CROPS_Question2', 'CROPS_Question3', 'CROPS_Question4', 'CROPS_Question5', 'CROPS_Question6',
        'CROPS_Question7', 'CROPS_Question8', 'CROPS_Question9', 'CROPS_Question10', 'CROPS_Question11', 'CROPS_Question12',
        'CROPS_Question13', 'CROPS_Question14', 'CROPS_Question15', 'CROPS_Question16', 'CROPS_Question17', 'CROPS_Question18',
        'CROPS_Question19', 'CROPS_Question20', 'CROPS_Question21', 'CROPS_Question22', 'CROPS_Question23', 'CROPS_Question24',
        'CROPS_Question25', 'CROPS_Question26'
    ]
}