export class Ncfas  {
    valueArr = [
        { ClientName: 'Client Name' },
        { DateOfIntake: 'Date of Intake' },
        { DateOfReunification: 'Date of Reunification' },
        { DateOfCasePlan1: 'Date of Case Plan1' },
        { DateOfCasePlan2: 'Date of Case Plan2' },
        { DateOfClosure: 'Date of Closure' },
        { CompletionDate: 'Administered Date' },
        { ParentName: 'Parent/Family Name' },
        { StaffName: 'Administered By' },
        { EnvironmentComment: 'Environment Comment' },
        { ParentalCapabilitiesComment: 'Parental Capabilities Comment' },
        { FamilyInteractionsComment: 'Family Interactions Comment' },
        { FamilySafetyComment: 'Family Safety Comment' },
        { ChildWell: 'ChildWell Comment' },
        { SocialCommunityLifeComment: 'Social Community Life Comment' },
        { Self: 'Self Comment' },
        { FamilyHealthComment: 'Family Health Comment' },
        { CaregiverChildAmbivalenceComment: 'Caregiver Child Ambivalence Comment' },
        { TextField2: 'Reunification Comment' },
        { title: 'Title' },
        { date: 'Date' },

    ]
    optionIndex = [
        { AssessmentReason: 'Assessment Reason' },
        { EnvironmentHousingStability: 'Housing Stability' },
        { EnvironmentSafety: 'Safety in the Community' },
        { EnvironmentRisks: 'Environmental Risks' },
        { EnvironmentHabitability: 'Habitability of Housing' },
        { EnvironmentHygiene: 'Personal Hygiene' },
        { EnvironmentLearning: 'Learning Environment' },
        { EnvironmentOverall: 'Overall Environment' },
        { ParentalCapabilitiesSupervision: 'Supervision of Child(ren)' },
        { ParentalCapabilitiesDisciplinary: 'Disciplinary Practices' },
        { ParentalCapabilitiesDevelopment: 'Provision of Developmental/Enrichment Opportunities' },
        { ParentalCapabilitiesDrugs: 'Use of Drugs/Alcohol Interferes with Parenting' },
        { ParentalCapabilitiesEducation: 'Promotes Child(ren)’s Education' },
        { ParentalCapabilitiesMedia: 'Controls Access to Media/Reading Material' },
        { ParentalCapabilitiesLiteracy: 'Parent(s)/Caregiver(s)’s Literacy' },
        { ParentalCapabilitiesOverall: 'Overall Parental Capabilities' },
        { FamilyInteractionsBonding: 'Bonding with Child(ren)' },
        { FamilyInteractionsCommunication: 'Communication with Child(ren)' },
        { FamilyInteractionsExpectation: 'Expectations of Child(ren)' },
        { FamilyInteractionsSupport: 'Mutual Support Within the Family' },
        { FamilyInteractionsRelationshipCaregiver: 'Relationship Between Parents/Caregivers' },
        { FamilyInteractionsRoutines: 'Family Routines/Rituals' },
        { FamilyInteractionsRecreation: 'Family Recreation and Play Activities' },
        { FamilyInteractionsOverall: 'Overall Family Interactions' },
        { FamilySafetyDomesticViolence: 'Absence/Presence of Domestic Violence Between Parents/Caregivers' },
        { FamilySafetyConflict: 'Absence/Presence of Other Family Conflict' },
        { FamilySafetyAbuse: 'Absence/Presence of Physical Abuse of Child(ren)' },
        { FamilySafetyEmotionalAbuse: 'Absence/Presence of Emotional Abuse of Child(ren)' },
        { FamilySafetySexualAbuse: 'Absence/Presence of Sexual Abuse of Child(ren)' },
        { FamilySafetyNeglect: 'Absence/Presence of Neglect of Child(ren)' },
        { FamilySafetyWeapons: 'Absence/Presence of Access to Weapons' },
        { FamilyInteractionsOverall: 'Overall Family Safety' },
        { ChildWellBeingBehavior: 'Child(ren)s Behavior' },
        { ChildWellBeingSchool: 'School Performance' },
        { ChildWellBeingRelationshipParents: 'Child(ren) Relationship with Parent(s)/Caregiver(s)' },
        { ChildWellBeingSiblings: 'hild(ren)s Relationship with Sibling(s)' },
        { ChildWellBeingPeers: 'Child(ren)s Relationship with Peers' },
        { ChildWellBeingMaintainFamily: 'Cooperation/Motivation to Maintain the Family' },
        { ChildWellBeingOverall: 'Overall Child Well-Being' },
        { SocialCommunityLifeSocial: 'Social relationships' },
        { SocialCommunityLifeExtracurricular: 'Relationships with Child Care, Schools, and Extracurricular Services' },
        { SocialCommunityLifeNeighborhood: 'Connection to Neighborhood, Cultural/Ethnic Community' },
        { SocialCommunityLifeSpirtual: 'Connection to Spiritual/Religious Community' },
        { SocialCommunityLifeHelp: 'Parent(s)/Caregiver(s) Initiative and Acceptance of Available Help/Support' },
        { SocialCommunityLifeOverall: 'Overall Child Well-Being6. Cooperation/Motivation to Maintain the Family' },
        { SelfSuffciencyEmployment: 'Caregiver Employment' },
        { SelfSuffciencyIncome: ' Family Income' },
        { SelfSuffciencyManagement: 'Financial Management' },
        { SelfSuffciencyFood: 'Food and Nutrition' },
        { SelfSuffciencyTransportation: 'Transportation' },
        { SelfSuffciencyOverall: 'Overall Child Well-Being' },
        { FamilyHealthParentsHealth: 'Parent(s)/Caregiver(s)s Physical Health' },
        { FamilyHealthParentsDisabilaty: 'Parent(s)/Caregiver(s) Disability' },
        { FamilyHealthParentsMentalHealth: 'Parents(s)/Caregiver(s) Mental Health' },
        { FamilyHealthChildrensHealth: 'Child(ren) Physical Health' },
        { FamilyHealthChildrensDisabilty: 'Child(ren) Disability' },
        { FamilyHealthChildrensMentalHealth: 'Child(ren) Mental Health' },
        { FamilyHealthAccessToMentalHealth: 'Family Access to Health/Mental Health Care' },
        { FamilyHealthOverall: 'Overall Family Health' },
        { CaregiverChildAmbivalenceParentAmbivalenceChild: 'Parent/Caregiver Ambivalence Toward Child' },
        { CaregiverChildAmbivalenceChildAmbvialenceParent: 'Child Ambivalence Towards Parent/Caregiver' },
        { CaregiverChildAmbivalenceSubCareProvider: 'Ambivalence Exhibited By Substitute Care Provider' },
        { CaregiverChildAmbivalenceDisruptedAttachment: 'Disrupted Attachment' },
        { CaregiverChildAmbivalencePreUnificationVisits: 'Pre-Reunification Home Visitations' },
        { CaregiverChildAmbivalenceOverall: 'Overall Caregiver/Child Ambivalence' },
        { ReadinessforReunificationCPS: 'Resolution of Significant CPS Risk Factors' },
        { ReadinessforReunificationCompletion: 'Completion of Case Service Plans' },
        { ReadinessforReunificationLegal: 'Resolution of Legal Issues' },
        { ReadinessforReunificationTreatmentNeeds: 'Parent/Caregiver Understanding of Child Treatment Needs' },
        { ReadinessforReunificationBackup: 'Established Back-Up Supports and/or Service Plans' },
        { ReadinessforReunificationOverall: 'Overall Readiness for Reunification' },
    ]
}