export class CasaOfficer {
    cellPh: any;
    changedBy: string;
    changedDate: number;
    email: any;
    enteredBy: string;
    enteredDate: number;
    firstName: string;
    genderID: any;
    lastName: string;
    mi: string;
    notes: string;
    fax: number;
    suffix:any;
    ssn:number;
    address:string;
    Unknown:any;
    cityID:any;
    stateID:any;
    zipcodeID:any;
    countyID:any;  
    pager:number;
    tribeID:any;
    ethnicityID:any;
    ext:number;
    workPh:number;
    acronym:boolean;
    deceased:any;
    contract_StateID: any;
}
