export class FosterCare {
    valueArr = [
        { ClientName: 'Client Name' },
        { CaseManager: 'Case Manager' },
        { DateOfPlacement: 'Date of Placement' },
        { CompletionDate: 'Date of Completion' },
        { FromTime: 'From' },
        { ToTime: 'To' },
        { ProviderID: 'Provider Name' },
        { FosterCareWorker: 'Foster Care Worker' },
        { KinshipWorker: 'Kinship Worker' },
        { LicensedPermanencySpecialist: 'Licensed Permanency Specialist' },
        { FamilySupportWorker: 'Family Support Worker' },
        { presentAtVisit: 'List those present at visit' },
        { personTypeField: 'Person Type' },
        { MedicationsNeedToBeFilled: 'What medications does the child have that need to be refilled' },
        { SFCSAssistFirst7Days: 'What needs do you (foster parent/kinship parent) have that SFCS can assist with in the first 7 days of placement?' },
        { DeescalationTatics: 'What are specific de-escalation tactics that work for the child?' },
        { KPHAppointmentsScheduled: 'Has the child had their KBH, Vision, and Dental Appointments scheduled? (If no, they need to be scheduled in the first 7 days)' },
        { CommunityResources: 'What community resources are available for the Foster/Kinship Home to utilize in times of crisis?' },
        { AppointmentType1: 'Appointment Type 1' },
        { AppointmentChild1: 'Appointment Child 1' },
        { AppointmentTime1: 'Appointment Time 1' },
        { AppointmentLocation1: 'Appointment Location 1' },
        { AppointmentType2: 'Appointment Type 2' },
        { AppointmentChild2: 'Appointment Child 2' },
        { AppointmentTime2: 'Appointment Time 2' },
        { AppointmentLocation2: 'Appointment Location 2' },
        { AppointmentType3: 'Appointment Type 3' },
        { AppointmentChild3: 'Appointment Child 3' },
        { AppointmentTime3: 'Appointment Time 3' },
        { AppointmentLocation3: 'Appointment Location 3' },
        { AppointmentType4: 'Appointment Type 4' },
        { AppointmentChild4: 'Appointment Child 4' },
        { AppointmentTime4: 'Appointment Time 4' },
        { AppointmentLocation4: 'Appointment Location 4' },
        { PreferredCommunication: 'Preferred method of communication' },
        { PhoneNumber: 'Preferred Contact Phone Number' },
        { InServiceDays: 'If you foster children are school aged, when are the days school is not in session due to in-services, vacations, etc., what are the child care plans for those days' },
        { DayCareOutings: 'If your child attends daycare, when does the child have daycare outings, if any?' },
    ];
}