export class Fp {
    valueArr = [
        { ClientName: 'Client Name' },
        { ReferralDate: 'Date of Referral' },
        { CaseActivityBeginDate: 'Date' },
        { FISMembers: 'List of FIS members' },
        { CasePlanDates: 'Case Plan begin/end date' },
        { SafetyPlanDates: 'Safety Plan begin/target date' },
        { StaffingDates: 'Date and begin time and end time of staffing and log entered by' },
        { ReasonForReferral: 'Reason for Referral' },
        { PreviousSupervisoryStaffing: 'Date of previous supervisory staffings and update from that staffing' },
        { Participants: 'Participants' },
        { Director: 'Director' },
        { Supervisor: 'Supervisor' },
        { TherapistCaseManager: 'Therapist/Case Manager' },
        { FPCaseManager: 'FP Case Manager' },
        { FamilySupportWorker: 'Family Support Worker' },
        { OtherParticipants: 'Other' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
    ];
    optionIndex = [
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },
        { ClientName: '' },

    ]
}