export class MaternalPaternal {
    valueArr = [
        { DateOfBirth: 'Clients DOB' },
        { InitialAssessment: 'Initial Assessment' },
        { ReviewDate: 'Assessment Review Date' },
        { Relation1: 'Relationship 1' },
        { Name1: 'Name 1' },
        { phone1: 'phone 1' },
        { LiveWithRelative1: 'Live With Relative 1' },
        { Comment1: 'Comment 1' },
        { CompletionDate: 'Date' },
        { Relation2: 'Relationship 2' },
        { Name2: 'Name 2' },
        { phone2: 'phone 2' },
        { LiveWithRelative2: 'Live With Relative 2' },
        { Comment2: 'Comment 2' },
        { Relation3: 'Relationship 3' },
        { Name3: 'Name 3' },
        { phone3: 'phone 3' },
        { LiveWithRelative3: 'Live With Relative 3' },
        { Comment3: 'Comment 3' },
        { Relation4: 'Relationship 4' },
        { Name4: 'Name 4' },
        { phone4: 'phone 4' },
        { LiveWithRelative4: 'Live With Relative 4' },
        { Comment4: 'Comment 4' },
        { Relation5: 'Relationship 5' },
        { Name5: 'Name 5' },
        { phone5: 'phone 5' },
        { LiveWithRelative5: 'Live With Relative 5' },
        { Comment5: 'Comment 5' },
        { Relation6: 'Relationship 6' },
        { Name6: 'Name 6' },
        { phone6: 'phone 6' },
        { LiveWithRelative6: 'Live With Relative 6' },
        { Comment6: 'Comment 6' },
        { Relation7: 'Relationship 7' },
        { Name7: 'Name 7' },
        { phone7: 'phone 7' },
        { LiveWithRelative7: 'Live With Relative 7' },
        { Comment7: 'Comment 7' },
        { Relation8: 'Relationship 8' },
        { Name8: 'Name 8' },
        { phone8: 'phone 8' },
        { LiveWithRelative8: 'Live With Relative 8' },
        { Comment8: 'Comment 8' },
        { Relation9: 'Relationship 9' },
        { Name9: 'Name 9' },
        { phone9: 'phone 9' },
        { LiveWithRelative9: 'Live With Relative 9' },
        { Comment9: 'Comment 9' },
        { Relation10: 'Relationship 10' },
        { Name10: 'Name 10' },
        { phone10: 'phone 10' },
        { LiveWithRelative10: 'Live With Relative 10' },
        { Comment10: 'Comment 10' },
        { Relation11: 'Relationship 11' },
        { Name11: 'Name 11' },
        { phone11: 'phone 11' },
        { LiveWithRelative11: 'Live With Relative 11' },
        { Comment11: 'Comment 11' },
    ];

    optionIndex = [
        { MaternalPaternal1: 'Maternal/Paternal 1' },
        { MaternalPaternal2: 'Maternal/Paternal 2' },
        { MaternalPaternal3: 'Maternal/Paternal 3' },
        { MaternalPaternal4: 'Maternal/Paternal 4' },
        { MaternalPaternal5: 'Maternal/Paternal 5' },
        { MaternalPaternal6: 'Maternal/Paternal 6' },
        { MaternalPaternal7: 'Maternal/Paternal 7' },
        { MaternalPaternal8: 'Maternal/Paternal 8' },
        { MaternalPaternal9: 'Maternal/Paternal 9' },
        { MaternalPaternal10: 'Maternal/Paternal 10' },
        { MaternalPaternal11: 'Maternal/Paternal 11' },
    ];
}