export class Plan {
  admissionDate: any;
  caseManager_Name: any;
  caseManager_Phone: any;
  cc_ReviewedBy: any;
  cc_ReviewedBy_StaffName: any;
  clientName: any;
  enteredBy: any;
  familySupportWorker_Name: any;
  familySupportWorker_Phone: any;
  familyTherapist_Name: any;
  familyTherapist_Phone: any;
  individualTherapist_Name: any;
  individualTherapist_Phone: any;
  integererventions: any;
  kaecses: any;
  licensed_ChangedBy: any;
  licensed_EnteredBy: any;
  licensed_EnteredBy_StaffName: any;
  other1_Name: any;
  other1_Phone: any;
  other2_Name: any;
  other2_Phone: any;
  physician_Name: any;
  physician_Phone: any;
  psychiatrist_Name: any;
  psychiatrist_Phone: any;
  relevantHistory: any;
  resourceWorker_Name: any;
  resourceWorker_Phone: any;
  sup_ReviewedBy: any;
  sup_ReviewedBy_StaffName: any;
  supervisor_Name: any;
  supervisor_Phone: any;
  unlicensed_ChangedBy: any;
  unlicensed_EnteredBy: any;
  unlicensed_EnteredBy_StaffName: any;
  whyDidParentGuardianNotParticipate: any;
  cc_ReviewedDate: any;
  dateOfCompletion: any;
  dob: any;
  enteredDate: any;
  licensed_ChangedDate: any;
  licensed_EnteredDate: any;
  sup_ReviewedDate: any;
  unlicensed_ChangedDate: any;
  unlicensed_EnteredDate: any;
  caseManager_PhoneTypeID: any;
  familySupportWorker_PhoneTypeID: any;
  parentGuardian1_PhoneTypeID: any;
  parentGuardian2_PhoneTypeID: any;
  resourceParent1_PhoneTypeID: any;
  resourceParent2_PhoneTypeID: any;
  resourceWorker_PhoneTypeID: any;
  supervisor_PhoneTypeID: any;
  caseManager_StaffID: any;
  familySupportWorker_StaffID: any;
  licensed_EnteredBy_StaffID: any;
  resourceWorker_StaffID: any;
  supervisor_StaffID: any;
  unlicensed_EnteredBy_StaffID: any;
  caseManagerSignature_ContactTypeID: any;
  childSignature_ContactTypeID: any;
  parentGuardian1Signature_ContactTypeID: any;
  parentGuardian2Signature_ContactTypeID: any;
  resourceParent1Signature_ContactTypeID: any;
  resourceParent2Signature_ContactTypeID: any;
  resourceWorker_ContactTypeID: any;
  supervisorSignature_ContactTypeID: any;
  casePlanGoalID: any;
  clientID: any;
  parentGuardian1_FamilyMemberID: any;
  parentGuardian2_FamilyMemberID: any;
  payorID: any;
  placementID: any;
  procodeID: any;
  provider_SponsorID: any;
  providerID: any;
  providerLocationID: any;
  resourceParent1_ProviderMemberID: any;
  resourceParent2_ProviderMemberID: any;
  SFAOfficeID: any;
  cc_ReviewedBy_StaffID: any;
  sup_ReviewedBy_StaffID: any;
  isKinship: boolean;
  isMentalHealth: boolean;
  isResidential: boolean;
  mentalHealthServices: any;
  parentGuardianParticipation: any;
  PlacementPlanID: any;
  placementReferralClientStrength = [];
  placementPlanID: any;
  placementReferralMedication = [];
  placementReferralVisitation = [];
  placementReferralClientProfile = [];
  placementReferralPreventativeMeasure = [];
  placementReferralAssessment = [];
  placementReferralAppointment = [];
  statusTypeID: any;
}

export class Autofetch {
  caseManager_StaffID: any;
  familySupportWorker_StaffID: any;
  resourceWorker_StaffID: any;
  supervisor_StaffID: any;
  casePlanGoalID: any;
  procodeID: any;
  payorID: any;
  provider_SponsorID: any;
  providerID: any;
  clientName: any;
  kaecses: any;
  dob: any;
  admissionDate: any;
  levelOfCare: any;
  casePlanGoal: any;
  contractingAgency: any;
  SFAOffice: any;
  caseManager_Phone: any;
  caseManager: any;
  familySupportWorker: any;
  supervisor: any;
  resourceFamily: any;
  resourceFamily_Phone: any;
  resourceFamily_Address: any;
  resourceFamily_City: any;
  resourceFamily_State: any;
  resourceFamily_Zipcode: any;
  sponsorName: any;
  resourceWorker: any;
  clientAllergies: any;
}

export class PlanOfAction {
  'servicesAndSupportID': any;
  'personTypeID': any;
  'dateInitiated': any;
  'notes': any;
}

export class OtherPlacementParticipants {
  'personTypeID': any;
  'contactTypeID': any;
  'notes': any;
  'name': any;
  'phone': any;
}
