export class FpAdminRequirements {
    childName: string;
    factsCase: string;
    conferenceDatesFro: number;
    conferenceDatesTo: number;
    effectiveDatesFrom: number;
    effectiveDatesTo: number;
    stateReason: string;
    listSiblings: string;
    isCandidate = false;
    isNonCandidate = false;
    imminentRisk: string;
    specialistSignature: string;
    date: number;
    isReferralYes = false;
    isReferralNo = false;
    documentedReason: string;
    primaryHealth: string;
    healthProviderAddress: string;
    otherHealthProvider: string;
    otherHealthProviderAddress: string;
    dentist: string;
    dentistAddress: string;
    optometrist: string;
    optometristAddress: string;
    mentalHealth: string;
    mentalHealthAddress: string;
    educationalAdvocate: string;
    educationalAdvocateAddress: string;
    connectionForSuccess: string;
    connectionAddress: string;
    isCurrentYes = false;
    isCurrentNo = false;
    dateLastKbh: number;
    isDiagnosisYes = false;
    isDiagnosisNo = false;
    dateDiagnosed: number;
    types: string;
    isHcbsYes = false;
    isHcbsNo = false;
    isHcbsNa = false;

    isDd = false;
    isSed = false;
    isTbi = false;
    isTa = false;
    isAutism = false;

    isDisabilityYes = false;
    isDisabilityNo = false;
    isDisabilityNa = false;
    isWrittenHealthYes = false;
    isWrittenHealthNo = false;
    isWrittenHealthNa = false;
    isReportRequestedYes = false;
    isReportRequestedNo = false;
    isReportRequestedNa = false;
    isFatherIncarceratedYes = false;
    isFatherIncarceratedNo = false;
    isMotherIncarceratedYes = false;
    isMotherIncarceratedNo = false;
    isChildAdjudicatedYes = false;
    isChildAdjudicatedNo = false;
    childAdjudicatedDate = false;
    highestGrade: string;
    caseName: any;
}
