export class ReintPpsReg {
    ChildName: string;
    Dob: any;
    EthnicGroup: string;
    MotherName: string;
    FatherName: string;
    Name: string;
    IsS = false;
    IsM = false;
    IsSep = false;
    IsD = false;
    IsW = false;
    LivingWith: string;
    StreetAddress: string;
    City: string;
    State: string;
    Zip: string;
    HomeTelephone: string;
    WorkTelephone: string;
    Ssn: string;
    DayToContactCaretaker: number;
    RelationshipToChild: string;
    Employer: string;
    AlternateContactName: string;
    StreetAddress1: string;
    City1: string;
    State1: string;
    Zip1: string;
    HomeTelephone1: string;
    WorkTelephone1: string;
    IsCasePlanAttachedYes = false;
    IsCasePlanAttachedNo = false;
    IsPlanAttachedYes = false;
    IsPlanAttachedNo = false;
    SpecialNeeds: string;
    Handicaps: string;
    TreatmentsRequirements: string;
    SchoolInformation: string;
    IsPertinentInformationYes = false;
    IsPertinentInformationNo = false;
    Explain: string;
    NameOfWorker: string;
    WorkerTelephone: string;
    WorkerSignature: string;
    Date: number;
    NameOfSupervisor: string;
    SupervisorTelephone: string;
    SupervisorSignature: string;
    Date1: number;

}
