export class CisCaseActivity {
    begindate: any;
    finalizedDate: string;
    proCode: string;
    endDate: any;
    contactType: string;
    program: string;
    facts: any;
    showMultiClient: boolean;
    ClientName: any;
    procodeTypeField: any;
    file: any;
    personTypeField: any;
    formName: string;
    staffName: string;
    multiClientValue: string;
    multiClient: string;
    staffNotes: any;
    id: string;
    personType: string;
    referralTypeID: number;
    contactTypeField: any;
    clientId: number;
    PDFDoc: any;
    referralId: number;
    created: number;
    beginDate: any;
    enddate: any;
    Signature: any;
    name: string;
    Kaecses: any;
    updated: number;
    uploadFileDate: string;
    staffId: number;
    procodeIdList: number[];
    status: string;
    person:any;
    contact:any;
    procodeType:any;
}
