export class FamilyMember {

    familyMemberID: any;
    entity: string;
    address: string;
    cellPh: string;
    changedBy: string;
    changedDate: string;
    citizenship: string;
    cityID: any;
    contract_StateID: any;
    countyID: any;
    deceasedDate: any;
    denomination: string;
    dob: any;
    educationLevelID: any;
    email: string;
    employer: string;
    enteredBy: string;
    enteredDate: number;
    ext: string;
    facts: string;
    fax: string;
    firstName: string;
    genderID: any;
    homePh: string;
    isUSCitizen: boolean;
    lastName: string;
    mi: string;
    notes: string;
    occupation: string;
    pager: string;
    primaryLanguageID: any;
    raceID: any;
    religionID: any;
    secondaryLanguageID: any;
    ssn: any;
    stateID: any;
    suffix: string;
    tenureID: any;
    workPh: string;
    zipcodeID: any;
    ethnicityID: any;
    tribeID: any;
    createdDate: number;
    unknownAddress: boolean;
    employmentStatusID: any;

}
