export class InitialFamily {
    valueArr = [
        { SFCSworker: 'SFCS Worker' },
        { dateTime: 'Date/Time' },
        { Location: 'Location' },
        { safetyConcerns: 'Desribe the safety concerns, contributing factors, and family’s strengths to mitigate the safety concerns' },
        { familyStrengths: 'Desribe the risk, family strengths and resources to mitigate the risk, and services needed or taken' },
        { AnnualHouseholdInput: 'Annual Household Income Input' },
        { NumberlivingHousehold: 'Number living in Household' },
        { InitialCasePlanDate: 'Initial Case Plan Date' },
        { InitialCasePlanTime: 'Initial Case Plan Time' },
        { InitialCasePlanNotes: 'Initial Case Plan Notes' },
        { NextCourtHearingDate: 'Next Court Hearing Date' },
        { NextCourtHearingTime: 'Next Court Hearing Time' },
        { NextCourtHearingNotes: 'Next Court Hearing Notes' },
        { NextVisitDate: 'Next Visit Date' },
        { NextVisitTime: 'Next Visit Time' },
        { NextVisitNotes: 'Next Visit Notes' },
        { ParentsCaregiversDate: 'Next Meeting with Parents/Caregivers Date' },
        { ParentsCaregiversTime: 'Next Meeting with Parents/Caregivers Time' },
        { ParentsCaregiversNotes: 'Next Meeting with Parents/Caregivers Notes' },
        { ParentquestionsComments: 'Parent(s) questions or comments' },
        { clientRightClient: 'CLIENT RIGHTS AND RESPONSIBILITIES Client Initials' },
        { clientRightGuardian: 'CLIENT RIGHTS AND RESPONSIBILITIES Guardian Initials' },
        { privacyClient: 'NOTICE OF PRIVACY PRACTICES Client Initials' },
        { privacyGuardian: 'NOTICE OF PRIVACY PRACTICES Guardian Initials' },
        { mandatedClient: 'MANDATED REPORTER Client Initials' },
        { mandatedGuardian: 'MANDATED REPORTER Guardian Initials' },
        { providerClient: 'PROVIDER NON-DISCRIMINATION ACT Client Initials' },
        { providerGuardian: 'PROVIDER NON-DISCRIMINATION ACT Guardian Initials' },
        { communicationClient: 'COMMUNICATION – SENSORY IMPAIRMENT Client Initials' },
        { communicationGuardian: 'COMMUNICATION – SENSORY IMPAIRMENT Guardian Initials' },
        { communicationSensoryImpairment: 'If Yes, Sensory Impairment' },
        { Provision: 'If Yes, Provision(s) Needed' },
        { proficiencyClient: 'COMMUNICATION – LIMITED ENGLISH PROFICIENCY Client Initials' },
        { proficiencyGuardian: 'COMMUNICATION – LIMITED ENGLISH PROFICIENCY Guardian Initials' },
        { Communication: 'If Yes, Communication Needs' },
        { PreferredLanguage: 'If Yes, Preferred Language' },
        { photographsSFCSstaffClient: 'PHOTOGRAPHS/AUDIO/VIDEO RECORDING BY SFCS STAFF Client Initials' },
        { photographsSFCSstaffGuardian: 'PHOTOGRAPHS/AUDIO/VIDEO RECORDING BY SFCS STAFF Guardian Initials' },
        { photographsSFCSNonstaffClient: 'Client Initials' },
        { photographsSFCSNonstaffGuardian: 'Guardian Initials' },
        // { phone3: 'AUDIO/VIDEO RECORDING/PHOTOGRAPHS BY NON-STAFF Client Initials' },
        // { phone3: 'AUDIO/VIDEO RECORDING/PHOTOGRAPHS BY NON-STAFF Guardian Initials' },
        { customerCareClient: 'CUSTOMER CARE Client Initials' },
        { customerCareGuardian: 'CUSTOMER CARE Guardian Initials' },
        { grievanceClient: 'GRIEVANCE Client Initials' },
        { grievanceGuardian: 'GRIEVANCE Guardian Initials' },
        { emailConsentClient: 'EMAIL CONSENT Client Initials' },
        { emailConsentGuardian: 'EMAIL CONSENT Guardian Initials' },
        { careServiceClient: 'CARE SERVICES Client Initials' },
        { careServiceGuardian: 'CARE SERVICES Guardian Initials' },
        { immunizationClient: 'IMMUNIZATION Client Initials' },
        { immunizationGuardian: 'IMMUNIZATION Guardian Initials' },
        { ClientSignature: 'Signature of Referred Family' },
        { CaregiverSignature: 'Parent/Caregiver Signature 1' },
        { CaregiverSignature1: 'Parent/Caregiver Signature 2' },
        { CaregiverSignature2: 'Parent/Caregiver Signature 3' },
        { CaregiverSignature3: 'Parent/Caregiver Signature 3' },
        { Signature1: 'Signature 1' },
        { Signature2: 'Signature 2' },
        { Signature3: 'Signature 3' },
        { dcfSignature1: 'DCF Licensed Permanency Specialist 1' },
        { dcfSignature2: 'DCF Licensed Permanency Specialist 2' },
        { dcfSignature3: 'DCF Licensed Permanency Specialist 3' },
        { SFCSSignature1: 'SFCS Licensed Permanency Specialist 1' },
        { SFCSSignature2: 'SFCS Licensed Permanency Specialist 2' },
        { SFCSSignature3: 'SFCS Licensed Permanency Specialist 3' },
    ];

    optionIndex = [
        { Rolesresponsiblities: 'Roles and responsiblities' },
        { homeplacement: 'Safety concerns idetified leading to out of home placement' },
        { SafetyPlan: 'Safety plan needed or updated by case team' },
        { Riskconcerns: 'Risk concerns identified leading to out of home placement.' },
        { ServicePlan: 'Service plan needed or updated by case team' },
        { AnnualHousehold: 'Annual Household Income' },
        { SingleParent: 'Single Parent Household' },
        { RelativeKinship: 'Relative/Kinship placement discussed and contact information gathered' },
        { Introduction: 'Introduction & Parents Guide to Case Planning Conferences (CFS 3049) explained and given to family' },
        { appointments: 'Set-up the following appointments' },
        { neededAssessments: 'All needed assessments started. (ex. child and family profile, ecomap, genogram, initial screening tool)' },
        { releasesSigned: 'All releases signed by parents. (ex. insurance, education, confidentiality)' },
        { questionsComments: 'Parent(s) questions or comments' },
        { sensoryImpairment: 'Client has sensory impairment' },
        { clientSensoryImpairment: 'Client has sensory impairment' }
    ];
}