export class UnacceptableConditions {
  isAdd = false;
  isADHD = false;
  isAggressionPhy = false;
  isAggressionVerbal = false;
  isCriminalActivity = false;
  isCruelToAnimals = false;
  isDefiesAuthHome = false;
  isDefiesAuthSchool = false;
  isFireStarter = false;
  isGangInvolvement = false;
  isHygiene = false;
  isLies = false;
  isOppositional = false;
  isProfanity = false;
  isRunnerDoesntReturn = false;
  isRunsLeaves = false;
  isTemperTantrums = false;
  isTheft = false;
  isTruancy = false;
  isVandalism = false;
  isDiagnosis = false;
  isAspergers = false;
  isAutism = false;
  isDevelopmentalDelays = false;
  isMentalRetardation = false;
  isPhysicalDisabilityHearing = false;
  isPhysicalNonAmb = false;
  isPhysicalDisOther = false;
  iisPhysicalDisaSpeech = false;
  isPhysicalDisVisual = false;
  isAllergies = false;
  isAsthma = false;
  isBedWetting = false;
  isDiabetes = false;
  isEatingDisorder = false;
  isEncopresis = false;
  isEnuresis = false;
  isHeartDisease = false;
  isHIV = false;
  isInfantPreTeam = false;
  isInfantDependenance = false;
  isMedicalCondition = false;
  isPregant = false;
  isSeizures = false;
  isSexualTransmitted = false;
  isTraumaticBrainInjury = false;
  isAnxietyDisorder = false;
  isBiPolarDisorder = false;
  isDepression = false;
  isObsessive = false;
  isPostTraumaticStress = false;
  isPsychoticEpisodes = false;
  isSelfInjurioys = false;
  isSuicideAttempt = false;
  isSuicideIdeation = false;
  isSuspectedVictim = false;
  isVictimEmotional = false;
  isVictimHuman = false;
  isVictimPhysical = false;
  isVictimSexualAbuse = false;
  isBedWettingVictim = false;
  isBothAttraction = false;
  isMasturbation = false;
  isSameSex = false;
  isSexAdjudicated = false;
  isSexCharged = false;
  isSexCompletedTreatment = false;
  isSexRegistry = false;
  isSexComments = false;
  isSexuallyActive = false;
  isSexuallyActs = false;
  isAlcoholAbuse = false;
  isAlcoholDependence = false;
  isAlocoholExperimentation = false;
  isCigarateSmoking = false;
  isDrugAbuse = false;
  isDrugDependence = false;
  isDrugExperimentation = false;
  isHuffing = false;

}

export class DefaultValues {
  breadcrumbs: any[] = [];
  discardTo: string;
  unacceptConditionIdList: any;
  providerId: number;
  currentDate: Date;
  staffName: string;
  unacceptConditionListData: any[];
  UADeletableData: any[] = [];
  isEdit: boolean;
}
