export class CisCourtAppear {
    CASA: any;
    CSO: any;
    Children: any;
    ClientName: any;
    CompletionDate: any;
    CountyAtty: any;
    Custody: any;
    DCF: any;
    Father: any;
    FatherAtty: any;
    FromTime: any;
    GAL: any;
    Grandparents: any;
    Judge1: any;
    Kaecses: any;
    Mother: any;
    MothersAtty: any;
    NextHearingDate: any;
    NextHearingJudge: any;
    NextHearingLocation: any;
    NextHearingTime: any;
    NextHearingType: any;
    NotesAndRecommendations: any;
    OtherOrders: any;
    Others: any;
    Placement: any;
    RadioButtonList: any;
    SFSCStaff: any;
    Signature: any;
    Visitation: any;
    beginDate: any;
    clientId: any;
    courtLocation: any;
    created: any;
    disable = false;
    disableAll = false;
    endDate: any;
    file: string;
    finalizedDate: any;
    formName: string;
    hearing: any;
    id: any;
    length: any;
    multiClient: string;
    name: string;
    placement: any;
    program: string;
    showMultiClient = false;
    staffId: string;
    staffName: string;
    status: string;
    updated: any;
    uploadFileDate: any;
}
