export class FpChangeOfStatus {
    caseName: string;
    caseNumber: number;
    dateOfReferral: number;
    date: number;

    isChangeOF = false;
    isCustodyStatus = false;
    isCINC = false;
    childrenName: string;
    caseNumberChecked: string;
    isPlacedDCF = false;
    isReleasedDCF = false;
    releasedDCF: string;
    isPlacedInformal = false;
    isReleasedInformal = false;
    releasedInformal: string;
    isPlacedDcfOOH = false;
    placedDcfOOH: string;
    isPlacedJJA = false;
    placedJJA: string;
    isPlacedJjaOOH = false;
    placedJjaOOH: string;
    isChangeTherapist = false;
    isCaseManager = false;
    isFamilySupportWorke = false;
    isAssignedToCase = false;
    current: string;
    newChange: string;
    cellNumber: string;
    isChangeOfCaseHead = false;
    changeOfCaseHead: string;
    city: string;
    country: string;
    zip: string;
    ischangeCaseHeadPhNo = false;
    changeCaseHeadPhNo: string;
    isResumption = false;
    resumptionDate: number;
    isDcfRequest = false;
    isFamilyRequest = false;
    isOther = false;
    comments: string;
    isOtherChange = false;
    briefExplanation: string;
    staffSignature: string;
}
