export class Psi {
    valueArr : any[] = [
        { ParentName: 'Name' },
        { ParentGender: 'Gender' },
        { ParentDOB: 'Date of Birth' },
        { ParentEthnicGroup: 'Ethnic Group' },
        { date: 'Todays Date' },
        // { RelationToClientOther: 'Other (specify)' },
        { DefensiveResponding: 'Defensive Responding' },
        { ParentDomain: 'Parent Domain' },
        { ParentChild: 'Parent-Child Difficult Interaction' },
        { DifficultChild: 'Difficult Child' },
        { totalStress: 'TOTAL STRESS' }
    ];
    optionIndex = [
        { MaritalStatus: 'Marital Status' },
        { CareGiverRelationToClient: 'Care Giver Relation' },
        { Question1: 'I often have the feeling that I cannot handle things very well' },
        { Question2: 'I find myself giving up more of my life to meet my childrens needs than I ever expected' },
        { Question3: 'I feel trapped by my responsibilities as a parent' },
        { Question4: 'Since having this child, I have been unable to do new and different things' },
        { Question5: 'Since having this child, I feel that I am almost never able to do things that I like to do' },
        { Question6: 'I am unhappy with the last purchase of clothing I made for myself' },
        { Question7: 'There are quite a few things that bother me about my life' },
        { Question8: 'Does your child seem happyHaving a child has caused more problems than I expected in my relationship with my spouse/parenting partnerDoes your child cry, scream, or have tantrums for long periods of time' },
        { Question9: ' I feel alone and without friends' },
        { Question10: 'When I go to a party, I usually expect not to enjoy myself' },
        { Question11: 'I am not as interested in people as I used to be' },
        { Question12: 'I dont enjoy things as I used to' },
        { Question13: 'My child rarely does things for me that make me feel good' },
        { Question14: 'When I do things for my child, I get the feeling that my efforts are not appreciated very much SA' },
        { Question15: 'My child smiles at me much less than I expected' },
        { Question16: 'Sometimes I feel my child doesnt like me and doesnt want to be close to me' },
        { Question17: 'My child is very emotional and gets upset easily' },
        { Question18: 'My child doesnt seem to learn as quickly as most children' },
        { Question19: 'My child doesnt seem to smile as much as most children' },
        { Question20: 'My child is not able to do as much as I expected' },
        { Question21: 'It takes a long time and it is very hard for my child to get used to new things' },
        { Question22: 'I feel that I am: (choose a response from the choices below)' },
        { Question23: 'I expected to have closer and warmer feelings for my child than I do, and this bothers me' },
        { Question24: 'Sometimes my child does things that bother me just to be mean' },
        { Question25: 'My child seems to cry or fuss more often than most children' },
        { Question26: 'My child generally wakes up in a bad mood' },
        { Question27: 'I feel that my child is very moody and easily upset' },
        { Question28: 'Compared to the average child, my child has a great deal of difficulty in getting used to changes in schedules or changes around the house' },
        { Question29: 'My child reacts very strongly when something happens that my child doesnt like' },
        { Question30: 'When playing, my child doesnt often giggle or laugh' },
        { Question31: 'My childs sleeping or eating schedule was much harder to establish than I expected' },
        { Question32: 'I have found that getting my child to do something or stop doing something is: (choose a response from the choices below)' },
        { Question33: 'Think carefully and count the number of things which your child does that bothers you. For example, dawdles, refuses to listen, overactive, cries, interrupts, fights, whines, etc.' },
        { Question34: 'There are some things my child does that really bothers me a lot' },
        { Question35: 'My childs behavior is more of a problem than I expected' },
        { Question36: 'My child makes more demands on me than most children' }
    ];
}